baseURL = "https://w.ranetkad.ru/"
title = "ranetkad"
theme = "hextra"

defaultContentLanguage = "ru"
enableRobotsTXT = true
enableGitInfo = true
enableInlineShortcodes = true
hasCJKLanguage = false

[outputs]
  home = ["html"]
  page = ["html"]
  section = ["html", "rss"]

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[taxonomies]
  tag = "tags"

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1
    title = "ranetkad"

[menu]
  [[menu.main]]
    name = "Networking"
    pageRef = "/networking"
    weight = 1
  [[menu.main]]
    name = "Linux"
    pageRef = "/linux"
    weight = 2
  [[menu.main]]
    name = "Storage"
    pageRef = "/storage"
    weight = 3
  [[menu.main]]
    name = "Glossary"
    pageRef = "/glossary"
    weight = 4
  [[menu.main]]
    name = "Search"
    weight = 5
    [menu.main.params]
      type = "search"
  [[menu.main]]
    name = "GitHub"
    weight = 6
    url = "https://github.com/ranetkad/wiki.ranetkad.ru"
    [menu.main.params]
      icon = "github"

[params]
  description = ""

  [params.navbar]
    displayTitle = true
    displayLogo = false
    width = "wide"

  [params.theme]
    default = "system"
    displayToggle = true

  [params.footer]
    enable = false
    displayCopyright = false
    displayPoweredBy = false

  displayUpdatedDate = true
  dateFormat = "2006-01-02"

  [params.search]
    enable = true
    type = "flexsearch"
    [params.search.flexsearch]
      index = "content"
      tokenize = "forward"

  [params.editURL]
    enable = false

  [params.toc]
    displayTags = false

  [params.highlight.copy]
    enable = true
    display = "hover"

  [params.page]
    width = "wide"
    [params.page.contextMenu]
      enable = false

  [params.comments]
    enable = false

  [params.math]
    enable = true

  [params.mermaid]
    enable = true
